/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#263143",
        "inverse-surface": "#d4e4fa",
        background: "#051424",
        "primary-container": "#4d8eff",
        "on-tertiary-fixed": "#131b2e",
        secondary: "#bcc7de",
        "on-error": "#690005",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#8990a8",
        "surface-container-high": "#1c2b3c",
        "tertiary-fixed-dim": "#bec6e0",
        outline: "#8c909f",
        "on-primary": "#002e6a",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        primary: "#adc6ff",
        "on-tertiary-container": "#22293d",
        "inverse-on-surface": "#233143",
        "inverse-primary": "#005ac2",
        tertiary: "#bec6e0",
        surface: "#051424",
        "surface-container-low": "#0d1c2d",
        error: "#ffb4ab",
        "surface-dim": "#051424",
        "surface-container": "#122131",
        "on-primary-fixed": "#001a42",
        "on-primary-container": "#00285d",
        "surface-variant": "#273647",
        "on-tertiary": "#283044",
        "secondary-fixed-dim": "#bcc7de",
        "primary-fixed": "#d8e2ff",
        "surface-container-lowest": "#010f1f",
        "on-background": "#d4e4fa",
        "secondary-container": "#3e495d",
        "on-secondary-container": "#aeb9d0",
        "on-secondary-fixed-variant": "#3c475a",
        "outline-variant": "#424754",
        "on-secondary-fixed": "#111c2d",
        "secondary-fixed": "#d8e3fb",
        "surface-container-highest": "#273647",
        "tertiary-fixed": "#dae2fd",
        "on-surface": "#d4e4fa",
        "surface-bright": "#2c3a4c",
        "surface-tint": "#adc6ff",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-primary-fixed-variant": "#004395",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        sm: "8px",
        md: "16px",
        unit: "4px",
        xl: "40px",
        xs: "4px",
        lg: "24px",
        gutter: "20px",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
};
